CREATE TABLE `erp_work_center` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工作中心ID',
  `work_center_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '中心编码',
  `work_center_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '中心名称',
  `work_center_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '1' COMMENT '中心类型',
  `department_id` bigint DEFAULT NULL COMMENT '部门ID',
  `location` varchar(200) DEFAULT NULL COMMENT '位置',
  `capacity_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '1' COMMENT '产能类型',
  `standard_capacity` decimal(18,4) DEFAULT '0.0000' COMMENT '标准产能',
  `capacity_unit` varchar(50) DEFAULT '小时' COMMENT '产能单位',
  `efficiency_rate` decimal(5,4) DEFAULT '1.0000' COMMENT '效率系数',
  `available_capacity` decimal(18,4) DEFAULT '0.0000' COMMENT '可用产能',
  `cost_center` varchar(100) DEFAULT NULL COMMENT '成本中心',
  `cost_per_hour` decimal(18,4) DEFAULT '0.0000' COMMENT '小时成本',
  `setup_time` decimal(10,2) DEFAULT '0.00' COMMENT '准备时间(分钟)',
  `teardown_time` decimal(10,2) DEFAULT '0.00' COMMENT '清理时间(分钟)',
  `is_active` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '1' COMMENT '是否启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在，1代表删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_work_center_code` (`work_center_code`),
  KEY `idx_work_center_name` (`work_center_name`),
  KEY `idx_department_id` (`department_id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='工作中心表';


CREATE TABLE `erp_process` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工序ID',
  `process_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '工序编码',
  `process_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '工序名称',
  `process_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '1' COMMENT '工序类型(1:加工 2:装配 3:检测 4:包装)',
  `workcenter_id` bigint DEFAULT NULL COMMENT '所属工作中心ID',
  `standard_time` decimal(8,2) DEFAULT '0.00' COMMENT '标准工时(小时)',
  `setup_time` decimal(8,2) DEFAULT '0.00' COMMENT '准备时间(小时)',
  `teardown_time` decimal(8,2) DEFAULT '0.00' COMMENT '收尾时间(小时)',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '状态(0:正常 1:停用)',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '删除标志(0:正常 1:删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_process_code` (`process_code`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='工序表';


CREATE TABLE `erp_process_route` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '工艺路线ID',
  `process_route_code` varchar(50) NOT NULL COMMENT '工艺路线编码',
  `process_route_name` varchar(200) NOT NULL COMMENT '工艺路线名称',
  `product_material_id` bigint NOT NULL COMMENT '产品物料ID',
  `product_material_name` varchar(200) NOT NULL COMMENT '产品物料名称',
  `version` varchar(20) NOT NULL COMMENT '版本号',
  `effective_date` date NOT NULL COMMENT '生效日期',
  `expiry_date` date DEFAULT NULL COMMENT '失效日期',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '状态（0草稿 1已确认 2已发布 3已作废）',
  `is_default` char(1) DEFAULT '0' COMMENT '是否默认版本（0否 1是）',
  `total_cycle_time` decimal(10,2) DEFAULT '0.00' COMMENT '总周期时间(分钟)',
  `total_setup_time` decimal(10,2) DEFAULT '0.00' COMMENT '总准备时间(分钟)',
  `total_processing_time` decimal(10,2) DEFAULT '0.00' COMMENT '总加工时间(分钟)',
  `total_move_time` decimal(10,2) DEFAULT '0.00' COMMENT '总移动时间(分钟)',
  `total_queue_time` decimal(10,2) DEFAULT '0.00' COMMENT '总等待时间(分钟)',
  `is_active` char(1) NOT NULL DEFAULT '1' COMMENT '是否启用（0否 1是）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在，1代表删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_process_route_code_version` (`process_route_code`,`version`),
  KEY `idx_product_material_id` (`product_material_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='工艺路线主表';

CREATE TABLE `erp_process_route_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '明细ID',
  `process_route_id` bigint NOT NULL COMMENT '工艺路线ID',
  `process_id` bigint NOT NULL COMMENT '工序',
  `operation_sequence` int NOT NULL COMMENT '工序顺序',
  `work_center_id` bigint NOT NULL COMMENT '工作中心ID',
  `equipment_id` bigint DEFAULT NULL COMMENT '设备',
  `mold_id` bigint DEFAULT NULL COMMENT '模具',
  `setup_time` decimal(10,2) DEFAULT '0.00' COMMENT '准备时间(分钟)',
  `processing_time` decimal(10,2) DEFAULT '0.00' COMMENT '加工时间(分钟)',
  `move_time` decimal(10,2) DEFAULT '0.00' COMMENT '移动时间(分钟)',
  `queue_time` decimal(10,2) DEFAULT '0.00' COMMENT '等待时间(分钟)',
  `cycle_time` decimal(10,2) DEFAULT '0.00' COMMENT '周期时间(分钟)',
  `labor_hours` decimal(10,2) DEFAULT '0.00' COMMENT '人工工时(小时)',
  `machine_hours` decimal(10,2) DEFAULT '0.00' COMMENT '机器工时(小时)',
  `is_critical` char(1) DEFAULT '0' COMMENT '是否关键工序（0否 1是）',
  `is_optional` char(1) DEFAULT '0' COMMENT '是否可选工序（0否 1是）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在，1代表删除）',
  PRIMARY KEY (`id`),
  KEY `idx_process_route_id` (`process_route_id`),
  KEY `idx_operation_sequence` (`operation_sequence`),
  KEY `idx_work_center_id` (`work_center_id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='工艺路线明细表';


CREATE TABLE `erp_mold` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `mold_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '模具编码',
  `mold_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '模具名称',
  `mold_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '模具类型',
  `mold_category` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '模具分类',
  `product_material_id` bigint NOT NULL COMMENT '产品物料ID',
  `storage_location_id` bigint DEFAULT NULL COMMENT '存储位置ID',
  `mold_weight` decimal(10,4) DEFAULT NULL COMMENT '模具重量(kg)',
  `mold_size` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '模具尺寸',
  `cavity_count` int DEFAULT '1' COMMENT '型腔数量',
  `max_shot_weight` decimal(10,4) DEFAULT NULL COMMENT '最大注塑重量(g)',
  `min_shot_weight` decimal(10,4) DEFAULT NULL COMMENT '最小注塑重量(g)',
  `design_life` int DEFAULT NULL COMMENT '设计寿命(次)',
  `current_usage_count` int DEFAULT '0' COMMENT '当前使用次数',
  `maintenance_cycle` int DEFAULT NULL COMMENT '维护周期(次)',
  `last_maintenance_date` date DEFAULT NULL COMMENT '上次维护日期',
  `next_maintenance_date` date DEFAULT NULL COMMENT '下次维护日期',
  `mold_status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '模具状态',
  `supplier_id` bigint DEFAULT NULL COMMENT '供应商',
  `purchase_date` date DEFAULT NULL COMMENT '采购日期',
  `purchase_price` decimal(18,4) DEFAULT NULL COMMENT '采购价格',
  `is_active` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '1' COMMENT '是否启用',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '0' COMMENT '删除标志(0:正常 1:删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mold_code` (`mold_code`),
  KEY `idx_product_material` (`product_material_id`),
  KEY `idx_mold_type` (`mold_type`),
  KEY `idx_mold_category` (`mold_category`),
  KEY `idx_storage_location` (`storage_location_id`),
  KEY `idx_mold_status` (`mold_status`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='模具表';

CREATE TABLE `erp_equipment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '设备ID',
  `equipment_code` varchar(50) NOT NULL COMMENT '设备编码',
  `equipment_name` varchar(200) NOT NULL COMMENT '设备名称',
  `equipment_model` varchar(200) DEFAULT NULL COMMENT '设备型号',
  `equipment_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '1' COMMENT '设备类型',
  `manufacturer` varchar(200) DEFAULT NULL COMMENT '制造商',
  `supplier_id` bigint DEFAULT NULL COMMENT '供应商ID',
  `work_center_id` bigint DEFAULT NULL COMMENT '工作中心ID',
  `purchase_date` date DEFAULT NULL COMMENT '购买日期',
  `warranty_expiry_date` date DEFAULT NULL COMMENT '保修到期日期',
  `depreciation_method` char(1) DEFAULT '1' COMMENT '折旧方法（1直线法 2加速折旧法）',
  `useful_life` int DEFAULT '0' COMMENT '使用年限',
  `original_value` decimal(18,2) DEFAULT '0.00' COMMENT '原值',
  `current_value` decimal(18,2) DEFAULT '0.00' COMMENT '现值',
  `capacity` decimal(18,4) DEFAULT '0.0000' COMMENT '产能',
  `capacity_unit` varchar(50) DEFAULT 'piece/hour' COMMENT '产能单位',
  `status` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0' COMMENT '状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标志（0代表存在，1代表删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_equipment_code` (`equipment_code`),
  KEY `idx_equipment_name` (`equipment_name`),
  KEY `idx_work_center_id` (`work_center_id`),
  KEY `idx_supplier_id` (`supplier_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备表';
